apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: keycloak
  namespace: keycloak
data:
  KEYCLOAK_ADMIN: a2V5Y2xvYWs= # Default admin username is "keycloak". You should change it.
  KEYCLOAK_ADMIN_PASSWORD: a2V5Y2xvYWs= # Default password is "keycloak". You should change it.
